apiVersion: v1
kind: Service
metadata:
  name: first-app-service
spec:
  selector:
    app: first-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2288
    # - protocol: TCP
    #   port: 81
    #   targetPort: 8081
  type: LoadBalancer
  # type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: first-app
      tier: backend
  template:
    metadata:
      labels:
        app: first-app
        tier: backend
    spec:
      containers:
      - name: first-app
        image: phambchungdev/k8s-app:1.1
        volumeMounts:
          - name: data-log
            mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /
            port: 2288
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      volumes:
        - name: data-log
          # emptyDir: {}
          hostPath:
            path: /data
            type: DirectoryOrCreate