apiVersion: v1
kind: Service
metadata:
  name: first-app-service
spec:
  selector:
    app: first-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    # - protocol: TCP
    #   port: 81
    #   targetPort: 8081
  type: LoadBalancer
  # type: NodePort
